// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package database

import (
	"context"
	"database/sql"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (author, title, html, url)
VALUES ($1, $2, $3, $4)
RETURNING id, author, title, html, url, created_at, updated_at, deleted_at
`

type CreateArticleParams struct {
	Author sql.NullString
	Title  sql.NullString
	Html   string
	Url    string
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Author,
		arg.Title,
		arg.Html,
		arg.Url,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Html,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArticle = `-- name: GetArticle :one
SELECT id, author, title, html, url, created_at, updated_at, deleted_at FROM articles
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Html,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArticleByURL = `-- name: GetArticleByURL :one
SELECT id, author, title, html, url, created_at, updated_at, deleted_at FROM articles
WHERE url = $1 AND deleted_at IS NULL
`

func (q *Queries) GetArticleByURL(ctx context.Context, url string) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleByURL, url)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Html,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserArticles = `-- name: GetUserArticles :many
SELECT articles.id, articles.author, articles.title, articles.html, articles.url, articles.created_at, articles.updated_at, articles.deleted_at
FROM articles
JOIN user_articles ON user_articles.article_id = articles.id
WHERE user_articles.user_id = $1
    AND articles.deleted_at IS NULL
`

func (q *Queries) GetUserArticles(ctx context.Context, userID int64) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, getUserArticles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Title,
			&i.Html,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
