// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Article struct {
	ID        int64
	Author    sql.NullString
	Title     sql.NullString
	Html      string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID    int64
	Name  string
	Email string
	// Password hash; never store plaintext passwords.
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type UserArticle struct {
	UserID    int64
	ArticleID int64
}
