// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_articles.sql

package database

import (
	"context"
)

const articleRelationExists = `-- name: ArticleRelationExists :one
SELECT EXISTS (
  SELECT 1
  FROM user_articles
  WHERE user_id = $1 AND article_id = $2
)
`

type ArticleRelationExistsParams struct {
	UserID    int64
	ArticleID int64
}

func (q *Queries) ArticleRelationExists(ctx context.Context, arg ArticleRelationExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, articleRelationExists, arg.UserID, arg.ArticleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkArticleToUser = `-- name: LinkArticleToUser :one
INSERT INTO user_articles (user_id, article_id)
VALUES ($1, $2)
ON CONFLICT (user_id, article_id)
DO NOTHING
RETURNING user_id, article_id
`

type LinkArticleToUserParams struct {
	UserID    int64
	ArticleID int64
}

func (q *Queries) LinkArticleToUser(ctx context.Context, arg LinkArticleToUserParams) (UserArticle, error) {
	row := q.db.QueryRowContext(ctx, linkArticleToUser, arg.UserID, arg.ArticleID)
	var i UserArticle
	err := row.Scan(&i.UserID, &i.ArticleID)
	return i, err
}
