// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_articles.sql

package database

import (
	"context"
)

const linkArticleToUser = `-- name: LinkArticleToUser :one
INSERT INTO user_articles (user_id, article_id)
VALUES ($1, $2)
RETURNING user_id, article_id
`

type LinkArticleToUserParams struct {
	UserID    int64
	ArticleID int64
}

func (q *Queries) LinkArticleToUser(ctx context.Context, arg LinkArticleToUserParams) (UserArticle, error) {
	row := q.db.QueryRowContext(ctx, linkArticleToUser, arg.UserID, arg.ArticleID)
	var i UserArticle
	err := row.Scan(&i.UserID, &i.ArticleID)
	return i, err
}
